### ISSUE TITLE
cffi exception on import, wanting GCC?

### ISSUE THREAD

**Issue by glyph** [habnabit/launchdcheckin#1]
this could well be a configuration issue in my environment, but:

```
>>> import launchdcheckin
In file included from /usr/include/launch.h:26,
                 from lib/python2.7/site-packages/launchdcheckin/__pycache__/_cffi__x8a87a8c1x6a470c9c.c:210:
/usr/include/xpc/base.h:64:20: error: missing binary operator before token "("
/usr/include/xpc/base.h:81:18: error: missing binary operator before token "("
In file included from /usr/include/launch.h:26,
                 from lib/python2.7/site-packages/launchdcheckin/__pycache__/_cffi__x8a87a8c1x6a470c9c.c:210:
/usr/include/xpc/base.h:64:20: error: missing binary operator before token "("
/usr/include/xpc/base.h:81:18: error: missing binary operator before token "("
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't figure out the architecture type of: /var/folders/_b/x45v368523bgyqbgql77h0xm0000gp/T//ccvTFoMd.out
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/glyph/.virtualenvs/tmp-809abf02091b1606/lib/python2.7/site-packages/launchdcheckin/__init__.py", line 4, in <module>
    from launchdcheckin._impl import LaunchData
  File "/Users/glyph/.virtualenvs/tmp-809abf02091b1606/lib/python2.7/site-packages/launchdcheckin/_impl.py", line 55, in <module>
    """)
  File "/Users/glyph/.virtualenvs/tmp-809abf02091b1606/lib/python2.7/site-packages/cffi/api.py", line 373, in verify
    lib = self.verifier.load_library()
  File "/Users/glyph/.virtualenvs/tmp-809abf02091b1606/lib/python2.7/site-packages/cffi/verifier.py", line 96, in load_library
    self._compile_module()
  File "/Users/glyph/.virtualenvs/tmp-809abf02091b1606/lib/python2.7/site-packages/cffi/verifier.py", line 192, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/Users/glyph/.virtualenvs/tmp-809abf02091b1606/lib/python2.7/site-packages/cffi/ffiplatform.py", line 38, in compile
    outputfilename = _build(tmpdir, ext)
  File "/Users/glyph/.virtualenvs/tmp-809abf02091b1606/lib/python2.7/site-packages/cffi/ffiplatform.py", line 65, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.ffiplatform.VerificationError: CompileError: command 'gcc-4.2' failed with exit status 1
```

**Comment by glyph** [comment]
setting `CC=cc` in my environment works around this. (maybe it's because I'm using python.org python and it's built with GCC?)

**Comment by habnabit** [comment]
I think that's probably the reason, yeah. I haven't used python.org python in a very long time, so I couldn't say just offhand. I'll try it myself.

**Comment by glyph** [comment]
I actually bumped to @ned-deily and chatted with him about this - pretty sure it's an interaction between cffi and the way python.org python is built for the mac.
